import jsPDF from 'jspdf';
import type {
  Evaluation,
  ExamTemplate,
  Candidate,
  Station,
  Circuit,
} from '../types';

// Font configuration for Arabic support
const FONT_NORMAL = 'helvetica';

/**
 * Generate PDF report for a single station evaluation
 */
export function generateStationReport(
  evaluation: Evaluation,
  candidate: Candidate,
  station: Station,
  examName: string,
  circuit?: Circuit
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont(FONT_NORMAL, 'bold');
  doc.text('OSCE Examination Report', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(14);
  doc.setFont(FONT_NORMAL, 'normal');
  doc.text(examName, pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Station info with circuit
  doc.setFontSize(12);
  doc.setFont(FONT_NORMAL, 'bold');
  const stationHeader = circuit
    ? `Circuit ${circuit.circuitNumber} | Station ${station.stationNumber}: ${station.name}`
    : `Station ${station.stationNumber}: ${station.name}`;
  doc.text(stationHeader, 20, y);
  y += 10;

  // Candidate info
  doc.setFont(FONT_NORMAL, 'normal');
  doc.text(`Candidate: ${candidate.name} (${candidate.candidateNumber})`, 20, y);
  y += 7;
  doc.text(`Examiner: ${evaluation.examinerName}`, 20, y);
  y += 7;

  const dateStr = evaluation.endTime
    ? new Date(evaluation.endTime).toLocaleDateString()
    : new Date(evaluation.startTime).toLocaleDateString();
  doc.text(`Date: ${dateStr}`, 20, y);
  y += 15;

  // Scores table header
  doc.setFont(FONT_NORMAL, 'bold');
  doc.text('Checklist Item', 20, y);
  doc.text('Score', 160, y);
  y += 5;

  // Draw line
  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
  y += 8;

  // Scores
  doc.setFont(FONT_NORMAL, 'normal');
  doc.setFontSize(10);

  // Group items by category
  const itemsByCategory = new Map<string, typeof station.checklistItems>();
  for (const item of station.checklistItems) {
    const category = item.category || 'General';
    if (!itemsByCategory.has(category)) {
      itemsByCategory.set(category, []);
    }
    itemsByCategory.get(category)!.push(item);
  }

  for (const [category, items] of itemsByCategory) {
    // Category header
    doc.setFont(FONT_NORMAL, 'bold');
    doc.setFontSize(11);
    doc.text(category, 20, y);
    y += 6;

    doc.setFont(FONT_NORMAL, 'normal');
    doc.setFontSize(10);

    for (const item of items) {
      const scoreEntry = evaluation.scores.find((s) => s.itemId === item.id);
      const score = scoreEntry?.score ?? '-';
      const maxScore = item.maxScore;

      // Truncate long text
      const text = item.text.length > 60 ? item.text.substring(0, 57) + '...' : item.text;
      doc.text(`  ${text}`, 20, y);
      doc.text(`${score}/${maxScore}`, 165, y);
      y += 6;

      // Check if we need a new page
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    }
    y += 4;
  }

  // Global Rating
  if (station.globalRatingEnabled && evaluation.globalRating !== undefined) {
    y += 5;
    doc.setFont(FONT_NORMAL, 'bold');
    doc.setFontSize(11);
    const ratingLabels: Record<number, string> = {
      0: 'Clear fail',
      1: 'Borderline',
      2: 'Pass',
      3: 'Good pass',
      4: 'Excellent',
    };
    doc.text(`Global Rating: ${evaluation.globalRating}/4 (${ratingLabels[evaluation.globalRating] || ''})`, 20, y);
    y += 10;
  }

  // Total Score
  y += 5;
  doc.setFont(FONT_NORMAL, 'bold');
  doc.setFontSize(12);
  const percentage = ((evaluation.totalScore / evaluation.maxPossibleScore) * 100).toFixed(1);
  doc.text(`Total Score: ${evaluation.totalScore}/${evaluation.maxPossibleScore} (${percentage}%)`, 20, y);
  y += 10;

  // Notes
  if (evaluation.notes) {
    y += 5;
    doc.setFont(FONT_NORMAL, 'bold');
    doc.text('Examiner Notes:', 20, y);
    y += 6;
    doc.setFont(FONT_NORMAL, 'normal');
    doc.setFontSize(10);

    // Word wrap notes
    const lines = doc.splitTextToSize(evaluation.notes, 170);
    for (const line of lines) {
      doc.text(line, 20, y);
      y += 5;
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont(FONT_NORMAL, 'normal');
    doc.text(
      `Generated by OSCE App - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  return doc;
}

/**
 * Generate summary report for a candidate across all stations
 */
export function generateCandidateSummaryReport(
  candidate: Candidate,
  evaluations: Evaluation[],
  exam: ExamTemplate,
  circuits?: Circuit[]
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Helper to find circuit by ID
  const getCircuit = (circuitId: string) => circuits?.find((c) => c.id === circuitId);

  // Header
  doc.setFontSize(18);
  doc.setFont(FONT_NORMAL, 'bold');
  doc.text('OSCE Candidate Summary Report', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(14);
  doc.setFont(FONT_NORMAL, 'normal');
  doc.text(exam.name, pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Candidate info
  doc.setFontSize(12);
  doc.setFont(FONT_NORMAL, 'bold');
  doc.text(`Candidate: ${candidate.name}`, 20, y);
  y += 7;
  doc.setFont(FONT_NORMAL, 'normal');
  doc.text(`Candidate Number: ${candidate.candidateNumber}`, 20, y);
  y += 7;
  if (candidate.group) {
    doc.text(`Group: ${candidate.group}`, 20, y);
    y += 7;
  }
  y += 10;

  // Station scores table - with Circuit column
  doc.setFont(FONT_NORMAL, 'bold');
  doc.setFontSize(10);
  doc.text('Station', 20, y);
  doc.text('Circuit', 85, y);
  doc.text('Score', 105, y);
  doc.text('%', 130, y);
  doc.text('Global', 145, y);
  doc.text('Examiner', 165, y);
  y += 5;

  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
  y += 8;

  doc.setFont(FONT_NORMAL, 'normal');
  doc.setFontSize(9);

  let totalScore = 0;
  let totalMaxScore = 0;

  for (const station of exam.stations) {
    const evaluation = evaluations.find((e) => e.stationId === station.id);

    const stationName = station.name.length > 20
      ? station.name.substring(0, 17) + '...'
      : station.name;

    doc.text(`${station.stationNumber}. ${stationName}`, 20, y);

    if (evaluation) {
      // Circuit number
      const circuit = getCircuit(evaluation.circuitId);
      doc.text(circuit ? `C${circuit.circuitNumber}` : '-', 85, y);

      const percentage = ((evaluation.totalScore / evaluation.maxPossibleScore) * 100).toFixed(0);
      doc.text(`${evaluation.totalScore}/${evaluation.maxPossibleScore}`, 105, y);
      doc.text(`${percentage}%`, 130, y);

      if (evaluation.globalRating !== undefined) {
        doc.text(`${evaluation.globalRating}/4`, 145, y);
      } else {
        doc.text('-', 145, y);
      }

      const examiner = evaluation.examinerName.length > 12
        ? evaluation.examinerName.substring(0, 10) + '...'
        : evaluation.examinerName;
      doc.text(examiner, 165, y);

      totalScore += evaluation.totalScore;
      totalMaxScore += evaluation.maxPossibleScore;
    } else {
      doc.text('-', 85, y);
      doc.text('Not evaluated', 105, y);
    }

    y += 7;

    if (y > 260) {
      doc.addPage();
      y = 20;
    }
  }

  // Overall total
  y += 5;
  doc.setLineWidth(0.5);
  doc.line(20, y, 190, y);
  y += 8;

  doc.setFont(FONT_NORMAL, 'bold');
  doc.setFontSize(12);
  const overallPercentage = totalMaxScore > 0
    ? ((totalScore / totalMaxScore) * 100).toFixed(1)
    : '0';
  doc.text(`Overall Total: ${totalScore}/${totalMaxScore} (${overallPercentage}%)`, 20, y);
  y += 10;

  // Pass/Fail determination (example: 50% pass mark)
  const passMark = 50;
  const passed = parseFloat(overallPercentage) >= passMark;
  doc.setFontSize(14);
  doc.setTextColor(passed ? 0 : 255, passed ? 128 : 0, 0);
  doc.text(`Result: ${passed ? 'PASS' : 'FAIL'}`, 20, y);
  doc.setTextColor(0, 0, 0);

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont(FONT_NORMAL, 'normal');
    doc.text(
      `Generated by OSCE App - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  return doc;
}

/**
 * Generate cohort summary report (all candidates)
 */
export function generateCohortReport(
  exam: ExamTemplate,
  candidates: Candidate[],
  allEvaluations: Evaluation[],
  circuits?: Circuit[]
): jsPDF {
  const doc = new jsPDF('landscape');
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Helper to find circuit by ID
  const getCircuit = (circuitId: string) => circuits?.find((c) => c.id === circuitId);

  // Helper to get candidate's circuit (from their first evaluation)
  const getCandidateCircuit = (candidateId: string): Circuit | undefined => {
    const eval_ = allEvaluations.find((e) => e.candidateId === candidateId);
    return eval_ ? getCircuit(eval_.circuitId) : undefined;
  };

  // Helper to truncate examiner name
  const truncateExaminer = (name: string, maxLen: number = 8): string => {
    if (name.length <= maxLen) return name;
    return name.substring(0, maxLen - 1) + '.';
  };

  // Header
  doc.setFontSize(16);
  doc.setFont(FONT_NORMAL, 'bold');
  doc.text('OSCE Cohort Summary Report', pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFontSize(12);
  doc.setFont(FONT_NORMAL, 'normal');
  doc.text(exam.name, pageWidth / 2, y, { align: 'center' });
  y += 5;
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Table header
  doc.setFontSize(7);
  doc.setFont(FONT_NORMAL, 'bold');

  let x = 5;
  const colWidths = {
    number: 20,
    name: 35,
    circuit: 10,
    stationScore: 12,
    stationExaminer: 18,
    total: 22,
    percent: 14,
    result: 14,
  };

  doc.text('Number', x, y);
  x += colWidths.number;
  doc.text('Candidate', x, y);
  x += colWidths.name;
  doc.text('Cir', x, y);
  x += colWidths.circuit;

  // Station columns (score + examiner for each)
  for (const station of exam.stations) {
    doc.text(`S${station.stationNumber}%`, x, y);
    x += colWidths.stationScore;
    doc.text(`S${station.stationNumber}Ex`, x, y);
    x += colWidths.stationExaminer;
  }

  doc.text('Total', x, y);
  x += colWidths.total;
  doc.text('%', x, y);
  x += colWidths.percent;
  doc.text('Result', x, y);

  y += 3;
  doc.setLineWidth(0.3);
  doc.line(5, y, pageWidth - 5, y);
  y += 4;

  // Data rows
  doc.setFont(FONT_NORMAL, 'normal');
  doc.setFontSize(6);

  for (const candidate of candidates) {
    x = 5;

    doc.text(candidate.candidateNumber, x, y);
    x += colWidths.number;

    const displayName = candidate.name.length > 18
      ? candidate.name.substring(0, 15) + '...'
      : candidate.name;
    doc.text(displayName, x, y);
    x += colWidths.name;

    // Circuit number
    const circuit = getCandidateCircuit(candidate.id);
    doc.text(circuit ? `${circuit.circuitNumber}` : '-', x, y);
    x += colWidths.circuit;

    let candidateTotal = 0;
    let candidateMax = 0;

    // Station scores and examiners
    for (const station of exam.stations) {
      const evaluation = allEvaluations.find(
        (e) => e.candidateId === candidate.id && e.stationId === station.id
      );

      if (evaluation) {
        const pct = ((evaluation.totalScore / evaluation.maxPossibleScore) * 100).toFixed(0);
        doc.text(`${pct}%`, x, y);
        x += colWidths.stationScore;
        doc.text(truncateExaminer(evaluation.examinerName), x, y);
        x += colWidths.stationExaminer;
        candidateTotal += evaluation.totalScore;
        candidateMax += evaluation.maxPossibleScore;
      } else {
        doc.text('-', x, y);
        x += colWidths.stationScore;
        doc.text('-', x, y);
        x += colWidths.stationExaminer;
      }
    }

    // Total
    if (candidateMax > 0) {
      doc.text(`${candidateTotal}/${candidateMax}`, x, y);
      x += colWidths.total;

      const totalPct = ((candidateTotal / candidateMax) * 100).toFixed(1);
      doc.text(`${totalPct}%`, x, y);
      x += colWidths.percent;

      const passed = parseFloat(totalPct) >= 50;
      doc.setTextColor(passed ? 0 : 255, passed ? 128 : 0, 0);
      doc.text(passed ? 'PASS' : 'FAIL', x, y);
      doc.setTextColor(0, 0, 0);
    } else {
      doc.text('-', x, y);
      x += colWidths.total;
      doc.text('-', x, y);
      x += colWidths.percent;
      doc.text('-', x, y);
    }

    y += 4;

    if (y > 190) {
      doc.addPage();
      y = 15;

      // Repeat header on new page
      doc.setFont(FONT_NORMAL, 'bold');
      doc.setFontSize(7);
      x = 5;
      doc.text('Number', x, y);
      x += colWidths.number;
      doc.text('Candidate', x, y);
      x += colWidths.name;
      doc.text('Cir', x, y);
      x += colWidths.circuit;
      for (const station of exam.stations) {
        doc.text(`S${station.stationNumber}%`, x, y);
        x += colWidths.stationScore;
        doc.text(`S${station.stationNumber}Ex`, x, y);
        x += colWidths.stationExaminer;
      }
      doc.text('Total', x, y);
      x += colWidths.total;
      doc.text('%', x, y);
      x += colWidths.percent;
      doc.text('Result', x, y);
      y += 3;
      doc.line(5, y, pageWidth - 5, y);
      y += 4;
      doc.setFont(FONT_NORMAL, 'normal');
      doc.setFontSize(6);
    }
  }

  // Statistics summary
  y += 10;
  doc.setFont(FONT_NORMAL, 'bold');
  doc.setFontSize(10);
  doc.text('Summary Statistics:', 10, y);
  y += 7;

  doc.setFont(FONT_NORMAL, 'normal');
  doc.setFontSize(9);

  // Calculate statistics
  let passCount = 0;
  let totalCandidates = 0;
  const percentages: number[] = [];

  for (const candidate of candidates) {
    let candidateTotal = 0;
    let candidateMax = 0;

    for (const station of exam.stations) {
      const evaluation = allEvaluations.find(
        (e) => e.candidateId === candidate.id && e.stationId === station.id
      );
      if (evaluation) {
        candidateTotal += evaluation.totalScore;
        candidateMax += evaluation.maxPossibleScore;
      }
    }

    if (candidateMax > 0) {
      const pct = (candidateTotal / candidateMax) * 100;
      percentages.push(pct);
      if (pct >= 50) passCount++;
      totalCandidates++;
    }
  }

  const avgScore = percentages.length > 0
    ? (percentages.reduce((a, b) => a + b, 0) / percentages.length).toFixed(1)
    : '0';
  const passRate = totalCandidates > 0
    ? ((passCount / totalCandidates) * 100).toFixed(1)
    : '0';

  doc.text(`Total Candidates: ${totalCandidates}`, 10, y);
  y += 5;
  doc.text(`Pass Rate: ${passRate}% (${passCount}/${totalCandidates})`, 10, y);
  y += 5;
  doc.text(`Average Score: ${avgScore}%`, 10, y);

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont(FONT_NORMAL, 'normal');
    doc.text(
      `Generated by OSCE App - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      200,
      { align: 'center' }
    );
  }

  return doc;
}

/**
 * Download PDF with a given filename
 */
export function downloadPDF(doc: jsPDF, filename: string): void {
  doc.save(filename);
}

/**
 * Open PDF in new tab for preview
 */
export function previewPDF(doc: jsPDF): void {
  const blob = doc.output('blob');
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
}
